title:            Asu'ya Tüyolar
tagline:          Araştırmacılar için bilgisayar, internet tüyoları
description:      Araştırmacılar için bilgisayar, internet tüyoları
#Comment out url when working locally to resolve base urls correctly
#url: http://ozank.github.io/asuyatuyolar
url: http://asuyatuyolar.org

# Owner/author information
author_ids: [ozan,  htss, ismail]
authors:
  ozan:
    name:           Ozan Keysan
    avatar:         ozan.jpg
    bio:            "ODTÜ"
    # Social networking links are used in author-bio sidebar. Update and remove as you like.
    home:     "http://ozan.keysan.me"
    twitter:  "asuya_tuyolar"
    facebook:
    github:         "ozank"
    linkedin:       "okeysan"
    # For Google Authorship https://plus.google.com/authorship
    google_plus:  101596327621803798644
  htss:
    name:           H. Tuğça Şener Şatır
    avatar:         htss.jpg
    bio:            "Queen Belfast Üniversitesi"
    home:     "https://plus.google.com/+HTugcaSenerSatir/posts"
    twitter:
    facebook:
    github:
    linkedin:
    # For Google Authorship https://plus.google.com/authorship
    google_plus:
  ismail:
    name:           İsmail Arı
    avatar:         ismailari.jpg
    bio:            ""
    home:     "http://ismailari.com"
    twitter:  "ismailari"
    facebook:
    github:
    linkedin:       "ismailari"
    # For Google Authorship https://plus.google.com/authorship
    google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-42934492-1
google_verify:      dN8jR-zjlsGtpJb7IMPjo82FnvijPWDRhejtHnQXr2U
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:        D81F4C18A6CB3018F64D7C827D953DFD

# Links to include in top navigation
# For external links add external: true
links:
  - title: ETİKETLER
    url: /tag
  - title: ARŞİV
    url: /articles
  - title: Bağlantılar
    url: /links
  - title: Hakkinda
    url: /about
  #- title: Made Mistakes
  #  url: http://mademistakes.com
  #  external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Istanbul
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:title.html

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less"]
